version: "3.7"

services:
  app:
    container_name: i-on-web
    image: app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OPERATION_MODE: "${OPERATION_MODE-core-data}"
        CORE_URL: "${CORE_URL-http://172.17.0.1:10023}"
        CORE_READ_TOKEN: "${CORE_READ_TOKEN-l7kowOOkliu21oXxNpuCyM47u2omkysxb8lv3qEhm5U}"
    ports:
      - 8080:8080