version: "3.7"

services:
  web_app:
    container_name: i-on-web
    image: web_app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        OPERATION_MODE: "${OPERATION_MODE-core-data}"
        CORE_URL: "${CORE_URL-http://172.17.0.1:10023}"
        CORE_READ_TOKEN: "${CORE_READ_TOKEN-l7kowOOkliu21oXxNpuCyM47u2omkysxb8lv3qEhm5U}"
        CORE_CLIENT_ID: "${CORE_CLIENT_ID-22dd1551-db23-481b-acde-d286440388a5}"
    ports:
      - 8080:8080