name: heroku_deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the staging branch
  push:
    branches: [ staging ]
  pull_request:
    branches: [ staging ]


jobs:
 
  build:
    
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0
        with:
          email: ${{secrets.HEROKU_EMAIL}}
          api_key: ${{secrets.HEROKU_API_KEY}}
          docker_compose_file: '.docker/docker-compose-heroku.yml' # Path to the folder where the docker-compose file is located
          heroku_apps: '[{"imagename":"web_app","appname":"i-on-web","apptype":"web"}]' # List of Docker Image name, Heroku app and Heroku app type