name: heroku_deploy

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the staging branch
  push:
    branches: [ staging , refactoring-mock-data ]
  pull_request:
    branches: [ staging ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build, Push and Deploy to Heroku #set the whatever name you want to this step
        id: heroku
        uses: snithyanantham/docker-compose-multiple-apps-heroku-deploy@v1.0  # use the latest version of the action
        with:
          email: ${{secrets.HEROKU_EMAIL}}
          api_key: ${{secrets.HEROKU_API_KEY}}
          docker_compose_file: '.docker/docker-compose-heroku.yml' # set the path to the folder where the docker-compose file is located
          heroku_apps: '[{"imagename":"web_app","appname":"web_app","apptype":"web"}]' # List of Docker Image name, Heroku app and Heroku app type