name: unit_tests

on:
  # Triggers the workflow on push or pull request events to main and staging
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]
  
  workflow_dispatch:

jobs:

  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Sequence of tasks that will be executed as part of the job
    steps:
        - uses: actions/checkout@v2
        - name: 'Install Node'
          uses: actions/setup-node@v1
        - name: Install dependencies
          run: npm --prefix ./project install
        - name: "Run Test"
          run: npm --prefix ./project run test
